version: '3'

services:
  # A postgres DB used to store data by the API server microservice.
  voting-app-database:
    image: postgres:14.5
    container_name: voting-app-database
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - voting-app-network

  # The API server microservice.
  # It writes logs directly to the Loki service, exposes metrics for the Prometheus
  # service and sends traces to the Grafana Alloy instance.
  voting-app-server:
    build:
     context: ./voting-App-Server
    container_name: voting-app-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - voting-app-database
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
    networks:
      - voting-app-network

  voting-app-client:
    build:
     context: ./voting-App-Client
    container_name: voting-app-client
    restart: always
    ports:
      - "3001:3001"
    networks:
      - voting-app-network       
  
  nginx:
    image: nginx:alpine
    container_name: voting-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - voting-app-client
      - voting-app-server
    networks:
      - voting-app-network

networks:
  voting-app-network:
    driver: bridge

volumes:
  postgres: